plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.18.1'
}

group = 'cn.luojunhui'
version = '2.4.0'

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity '2024.2.6'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    sourceCompatibility = '21'
    targetCompatibility = '21'
}

intellijPlatform {
    pluginConfiguration {
        version = project.version
        ideaVersion {
            sinceBuild = '242'
        }
    }
}
